2019-12-08 01:12:06,842 - ERROR - Traceback (most recent call last):
  File "F:\python\duobaodao\Getgoods.py", line 205, in getUsedNo
    self.cursor.execute(sql)
  File "F:\python\duobaodao\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "F:\python\duobaodao\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "F:\python\duobaodao\lib\site-packages\pymysql\connections.py", line 516, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "F:\python\duobaodao\lib\site-packages\pymysql\connections.py", line 750, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')

2019-12-08 23:04:36,184 - ERROR - Traceback (most recent call last):
  File "F:\python\duobaodao\Getgoods.py", line 205, in getUsedNo
    # 发生错误时回滚
  File "F:\python\duobaodao\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "F:\python\duobaodao\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "F:\python\duobaodao\lib\site-packages\pymysql\connections.py", line 516, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "F:\python\duobaodao\lib\site-packages\pymysql\connections.py", line 750, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')

2019-12-20 13:47:43,497 - ERROR - Traceback (most recent call last):
  File "F:\python\duobaodao\Getgoods.py", line 244, in __getGoods
    if result_dict["data"]["auctionInfos"]:
TypeError: 'NoneType' object is not subscriptable

